name: construct_diet
description: Construct Diet
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dynamic_theme: ^1.0.1
  material_design_icons_flutter: ^3.2.3695
  md2_tab_indicator: ^1.0.2
  scoped_model: ^1.0.1
  url_launcher: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
