name: construct_diet
description: Construct Diet
version: 1.1.0+10
environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dynamic_theme: ^1.0.1
  material_design_icons_flutter: ^3.2.3695
  md2_tab_indicator: ^1.0.2
  scoped_model: ^1.0.1
  url_launcher: ^5.1.0
  shared_preferences: ^0.5.3+4
  package_info: ^0.4.0+6
  http: ^0.11.3+16

dev_dependencies:
  flutter_launcher_icons: "^0.7.2"
  flutter_test:
    sdk: flutter

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/icon.png"
  image_path_android: "assets/launcher/icon.png"
  adaptive_icon_background: "assets/launcher/background.png"
  adaptive_icon_foreground: "assets/launcher/foreground.png"

flutter:
  uses-material-design: true
  fonts:
    - family: SFUIDisplay-Black
      fonts:
        - asset: fonts/SFUIDisplay-Black.ttf

    - family: SFUIDisplay-Bold
      fonts:
        - asset: fonts/SFUIDisplay-Bold.ttf

    - family: SFUIDisplay-Heavy
      fonts:
        - asset: fonts/SFUIDisplay-Heavy.ttf

    - family: SFUIDisplay-Light
      fonts:
        - asset: fonts/SFUIDisplay-Light.ttf

    - family: SFUIDisplay-Medium
      fonts:
        - asset: fonts/SFUIDisplay-Medium.ttf

    - family: SFUIDisplay-Regular
      fonts:
        - asset: fonts/SFUIDisplay-Regular.ttf

    - family: SFUIDisplay-Semibold
      fonts:
        - asset: fonts/SFUIDisplay-Semibold.ttf

    - family: SFUIDisplay-Thin
      fonts:
        - asset: fonts/SFUIDisplay-Thin.ttf

    - family: SFUIDisplay-Ultralight
      fonts:
        - asset: fonts/SFUIDisplay-Ultralight.ttf

    - family: SFUIText-Bold
      fonts:
        - asset: fonts/SFUIText-Bold.ttf

    - family: SFUIText-Heavy
      fonts:
        - asset: fonts/SFUIText-Heavy.ttf

    - family: SFUIText-Light
      fonts:
        - asset: fonts/SFUIText-Light.ttf

    - family: SFUIText-Medium
      fonts:
        - asset: fonts/SFUIText-Medium.ttf

    - family: SFUIText-Regular
      fonts:
        - asset: fonts/SFUIText-Regular.ttf

    - family: SFUIText-Semibold
      fonts:
        - asset: fonts/SFUIText-Semibold.ttf
