name: construct_diet
description: Construct Diet
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dynamic_theme: ^1.0.1
  material_design_icons_flutter: ^3.2.3695
  md2_tab_indicator: ^1.0.2
  scoped_model: ^1.0.1
  url_launcher: ^5.1.0
  shared_preferences: ^0.5.3+4

dev_dependencies:
  flutter_launcher_icons: "^0.7.2"
  flutter_test:
    sdk: flutter

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/icon.png"
  image_path_android: "assets/launcher/icon.png"
  adaptive_icon_background: "assets/launcher/background.png"
  adaptive_icon_foreground: "assets/launcher/foreground.png"

flutter:
  uses-material-design: true
